### ISSUE TITLE
net::ssh 2.10. causes deployment to fail with git:wrapper wrong number of arguments (5 for 4)

### ISSUE THREAD

**Issue by kwisatz** [capistrano/sshkit#269] opened 2015-08-03 10:46 UTC
With net:ssh 2.10.x the deployment fails with a "wrong number of arguments (5 for 4)" exception.
Pinning net:ssh to 2.9.2 makes it work again.

Here's a full trace:

```bash
+ bundle install
Fetching gem metadata from https://rubygems.org/......
Resolving dependencies...
Installing rake 10.4.2
Installing i18n 0.7.0
Installing colorize 0.7.7
Installing net-ssh 2.10.0
Installing net-scp 1.2.1
Installing sshkit 1.7.1
Installing capistrano 3.2.1
Using bundler 1.7.4
Your bundle is complete!
It was installed into ./vendor/bundle
Post-install message from capistrano:
Capistrano 3.1 has some breaking changes, like `deploy:restart` callback should be added manually to your deploy.rb. Please, check the CHANGELOG: http://goo.gl/SxB0lr

If you're upgrading Capistrano from 2.x, we recommend to read the upgrade guide: http://goo.gl/4536kB
+ bundle exec cap staging deploy --trace
** Invoke staging (first_time)
** Execute staging
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke deploy (first_time)
** Execute deploy
** Invoke deploy:starting (first_time)
** Execute deploy:starting
** Invoke deploy:check (first_time)
** Execute deploy:check
** Invoke git:check (first_time)
** Invoke git:wrapper (first_time)
** Execute git:wrapper
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deployer@caladan: wrong number of arguments (5 for 4)
/opt/jenkins/workspace/FDE - Staging - Merge and UnitTest and Deploy/vendor/bundle/ruby/1.9.1/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:16:in `rescue in block (2 levels) in execute'
/opt/jenkins/workspace/FDE - Staging - Merge and UnitTest and Deploy/vendor/bundle/ruby/1.9.1/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
ArgumentError: wrong number of arguments (5 for 4)
/usr/lib/ruby/1.9.1/socket.rb:236:in `tcp'
/opt/jenkins/workspace/FDE - Staging - Merge and UnitTest and Deploy/vendor/bundle/ruby/1.9.1/gems/net-ssh-2.10.0/lib/net/ssh/transport/session.rb:70:in `initialize'
/opt/jenkins/workspace/FDE - Staging - Merge and UnitTest and Deploy/vendor/bundle/ruby/1.9.1/gems/net-ssh-2.10.0/lib/net/ssh.rb:221:in `new'
/opt/jenkins/workspace/FDE - Staging - Merge and UnitTest and Deploy/vendor/bundle/ruby/1.9.1/gems/net-ssh-2.10.0/lib/net/ssh.rb:221:in `start'
/opt/jenkins/workspace/FDE - Staging - Merge and UnitTest and Deploy/vendor/bundle/ruby/1.9.1/gems/sshkit-1.7.1/lib/sshkit/backends/connection_pool.rb:50:in `call'
/opt/jenkins/workspace/FDE - Staging - Merge and UnitTest and Deploy/vendor/bundle/ruby/1.9.1/gems/sshkit-1.7.1/lib/sshkit/backends/connection_pool.rb:50:in `create_new_entry'
/opt/jenkins/workspace/FDE - Staging - Merge and UnitTest and Deploy/vendor/bundle/ruby/1.9.1/gems/sshkit-1.7.1/lib/sshkit/backends/connection_pool.rb:22:in `checkout'
/opt/jenkins/workspace/FDE - Staging - Merge and UnitTest and Deploy/vendor/bundle/ruby/1.9.1/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:187:in `with_ssh'
/opt/jenkins/workspace/FDE - Staging - Merge and UnitTest and Deploy/vendor/bundle/ruby/1.9.1/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:137:in `block in _execute'
/opt/jenkins/workspace/FDE - Staging - Merge and UnitTest and Deploy/vendor/bundle/ruby/1.9.1/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `tap'
/opt/jenkins/workspace/FDE - Staging - Merge and UnitTest and Deploy/vendor/bundle/ruby/1.9.1/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `_execute'
/opt/jenkins/workspace/FDE - Staging - Merge and UnitTest and Deploy/vendor/bundle/ruby/1.9.1/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:66:in `execute'
/opt/jenkins/workspace/FDE - Staging - Merge and UnitTest and Deploy/vendor/bundle/ruby/1.9.1/gems/capistrano-3.2.1/lib/capistrano/tasks/git.rake:17:in `block (3 levels) in <top (required)>'
/opt/jenkins/workspace/FDE - Staging - Merge and UnitTest and Deploy/vendor/bundle/ruby/1.9.1/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/opt/jenkins/workspace/FDE - Staging - Merge and UnitTest and Deploy/vendor/bundle/ruby/1.9.1/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `run'
/opt/jenkins/workspace/FDE - Staging - Merge and UnitTest and Deploy/vendor/bundle/ruby/1.9.1/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => git:check => git:wrapper
The deploy has failed with an error: #<SSHKit::Runner::ExecuteError: Exception while executing as deployer@caladan: wrong number of arguments (5 for 4)>
** Invoke deploy:failed (first_time)
** Execute deploy:failed
```

**Comment by leehambley** [comment] 2015-08-03 11:22
Thanks for the heads-up. For what it's worth, we always take as loose as possible version requirements with our gems, etc. As Bundler requires us to be in the Gemfile, if we are speficially requesting some version of Net:SSH, or other, we run the risk of imposing an artificial runtime dependency on something that a user's application might legitimately require to be at another version. 

The price, unfortunately of doing that is occasoinal incompatibilities that would be caught by the [pessimistic-version-operator](https://robots.thoughtbot.com/rubys-pessimistic-operator). 

We've found over the years that this way of loosely defining our dependencies fails less often than the alternative.

Sorry you were bitten by it, I'll see if I can find the root cause, and fix it in a way that works for both version of Net:SSH pre-and-post 2.10.x

**Comment by kwisatz** [comment] 2015-08-03 13:01
On 03/08/15 13:22, Lee Hambley wrote:
> Sorry you were bitten by it, I'll see if I can find the root cause,
> and fix it in a way that works for both version of Net:SSH
> pre-and-post 2.10.x 
Great, thanks!

I always like to think that, when APIs change in a way that makes
consumers fail, their developers should announce the hell out of that.

But I guess bug reports work just as well ;)

**Comment by leehambley** [comment] 2015-08-03 13:12
> I always like to think that, when APIs change in a way that makes
consumers fail, their developers should announce the hell out of that.

Indeed, we could have locked the Net::SSH dependency at `~> 2.9.x` but then if your application, or anything else that you needed for production would be bound at an arbitrary version just because one of your development/deployment tools needed it, it's a shame that gem groups don't resolve dependencies individually, so we could lock Net:SSH, for your `:Development` group, without forcing that constraint on your *application*

**Comment by mattbrictson** [comment] 2015-08-03 21:47
This is because net-ssh 2.10 has dropped support for Ruby 1.9.3. `Socket.tcp` accepts up to 5 arguments in Ruby 2, but only 4 arguments in Ruby 1.9; hence the error you are seeing.

If you add `gem "net-ssh", "~> 2.9.2"` in your Gemfile, you should be fine.

As @leehambley explained, we can't force this limitation in SSHKit itself, but perhaps we can print a warning message if we detect you are running Ruby 1.9.3. Once the final version of net-ssh 2.10 is released (it is at RC1 right now), I imagine a lot of SSHKit users will run into this when they run `bundle update`.

**Comment by mattbrictson** [comment] 2015-08-03 21:55
FYI: net-ssh 2.10.0 was just [yanked](https://github.com/net-ssh/net-ssh/issues/260#issuecomment-127331322) and replaced with 2.10.1.rc1 in part because the Ruby 2 requirement was not properly set in the gemspec.

Now that the Ruby 2 requirement is in the 2.10.x gemspec, this means that from now on Ruby 1.9.3 users will safely remain on net-ssh 2.9.x even if they `bundle update`.

Since this has been resolved upstream, do you agree we can close this issue, @kwisatz ?

**Comment by leehambley** [comment] 2015-08-04 05:50
Good catch @mattbrictson I'd vote for closing this, although RIP all the people who now have a broken Gemset and won't know why :(

**Closed** 2015-08-10 09:37 UTC
