### ISSUE TITLE
Problem with "bundle install"

### ISSUE THREAD

**Issue by mateuszgorniak** [capistrano/sshkit#302] opened 2015-12-03 11:37 UTC
Hi everyone!
I use "capistrano-unicorn-nginx" gem to deploy and set up everything. After updating to `sshkit 1.8` following problem appears:
```
bundle stdout: Nothing written
bundle stderr: rbenv: version `2.2.3' is not installed (set by RBENV_VERSION environment variable)
/gems/sshkit-1.8.0/lib/sshkit/runners/parallel.rb:16:in `rescue in block (2 levels) in execute'
/gems/sshkit-1.8.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
```

Nothing else changed. I've even try to downgrade to `1.7.1` and it works fine.
Any possible solution how to fix it? I haven't notice any changes could break it in the changelog.

**Comment by leehambley** [comment] 2015-12-03 11:40
Do you have a more complete output?

**Comment by rudylee** [comment] 2015-12-03 11:41
I think is related to my issue #303

**Comment by mattbrictson** [comment] 2016-01-16 19:17
Closing as likely duplicate of #303.

**Closed by mattbrictson** 2016-01-16 19:17 UTC
