### ISSUE TITLE
upload!() should honor within()

### ISSUE THREAD

**Issue by docwhat** [capistrano/sshkit#89] opened 2014-01-07 15:59 UTC
The `upload!()` (and `download()`) methods should both honor `within()` for relative paths.

Example:

```
within '/tmp/' do
  upload! '/etc/hosts', 'should-be-in-tmp'
end
```

I expect the file `should-be-in-tmp` to be in `/tmp/` but instead it is in the user's home directory.

Ciao!

**Comment by mikz** [comment] 2016-02-24 10:21
Duplicate of #329 which is more active.

**Comment by leehambley** [comment] 2016-02-24 10:32
Thanks for the GC hint @docwhat

**Closed** 2016-02-24 10:31 UTC
