### ISSUE TITLE
Bug in `as` group implementation

### ISSUE THREAD

**Issue by pblesi** [capistrano/sshkit#424] opened 2018-05-11 04:21 UTC
As far as I can tell, specifying group in an `as` block will not work due to a quoting bug.

Based on this [commit](https://github.com/capistrano/sshkit/commit/c464c9756ff56912c430291fc2bcb437401a56aa) of the group functionality, it seems that the escaping of the double quotes was necessary because the sudo command used double quotes. As of this [commit](https://github.com/capistrano/sshkit/commit/fbe177541288720e927292e4b7a6141031cd8a56#diff-4eaa2c55e6802df7b49a8e7a2f7584d5) single quotes for sudo are used and the double quotes for the command are incorrectly escaped.

If this is indeed correct, I can look to post a PR that fixes the issue, but I did not want to bother with a fix in case there is something I'm missing.

**Comment by leehambley** [comment] 2018-05-11 07:54
> Based on this commit of the group functionality, it seems that the escaping of the double quotes was necessary because the sudo command used double quotes.

Sounds totally plausible, what's the usecase for executing something `as` a group, is it a "hack" to make sure to set group ownershp/etc? I quoted "hack" because `as` was intended for users.

Looking forward to getting a plan

**Comment by pblesi** [comment] 2018-05-11 22:58
Yeah, I'm developing a DSL that leverages SSHKit and am trying to expose the various functionality it provides, so allowing users to pass group to the [as method](https://github.com/capistrano/sshkit/blob/master/lib/sshkit/backends/abstract.rb#L98-L116)
I don't have a specific use case outside of the one indicated in this [example](https://github.com/capistrano/sshkit/blob/master/EXAMPLES.md#run-a-command-with-a-different-effective-group-id)

I'll go ahead and open a PR to modify the functionality

**Comment by mattbrictson** [comment] 2018-05-31 19:20
Fixed via #425

**Closed by mattbrictson** 2018-05-31 19:20 UTC
