### ISSUE TITLE
Control STDIN for individual command executions

### ISSUE THREAD

**Issue by vivid-inc** [capistrano/sshkit#216] opened 2015-01-24 06:20 UTC
Feature request! Two humble, rudimentary use cases, the abstractions of which are of high value to us:

1) A laundry list of system admin commands is written in a Ruby script, almost all of which require privileged access to run properly. A sudoers.d configuration file permits these certain system maintenance commands to be executed without password; a dangerous practice. Instead, with SSHKit, scripts can start with `sudo -v' to update the user's cached credentials, and subsequent commands have a plain `sudo' command-map prefix so that they can still run correctly. The key change being when `sudo -v' is run, the script can prompt the user for their password, subsequently piping that input to sudo's STDIN, something like this:

```ruby
execute(:sudo, '-v') do |context|
    password = STDIN.noecho(&:gets).chomp
    context.stdin.send_data(password) # Textual. `sudo' eventually next receives EOF, somehow.
end
```

2) Customer data is protected from intrusions by virtue of the data-at-rest being encrypted. That data is periodically processed, but must be decrypted first, and the corresponding secret key material must never be able to touch disk (assume swap is encrypted) or be visible (i.e. arguments in the process table). With SSHKit, the automation script can obtain the secret key from the local system and pipe it into the program's STDIN, thereby reducing the potential for ... mishaps on the remote system.

```ruby
execute(:process_customer_data, "--secret_key=- args ...") do |context|
    context.stdin.send_data(secret_key) # Binary blob. Again, STDIN EOF somehow follows
end
```

Thanks for your hard work on the fabulous SSHKit. We are looking at rewriting all automation scripts with something, and this feature would seal the deal for SSHKit.

**Comment by leehambley** [comment] 2015-01-26 12:55
I'd be more than happy to merge this if you can also add something to EXAMPLES and to the readme. I'd appreciate if it was worded to apply caution.

I'd also feel *much* better if you could add some tests, using `StringIO` to test that in a simple way would be ideal, even if you just `cat somefile` and write tostdin, and assert that the file has the correct contents.

The test suite spins up real VMs.

**Comment by robd** [comment] 2015-04-21 20:43
Hi @vivid-inc 

I'm looking at adding support for user interactions in #234. I'm pretty sure it will support the sudo use case you mention and I think it could support the `process_customer_data` case too. Would you be happy to close this issue if #234 was merged?

Any feedback much appreciated.

**Comment by vivid-inc** [comment] 2015-04-21 23:48
Thank you for this. Haven't got the time at the moment to confirm whether this PR solves #218; I can say definitively after we perform a rewrite, which, given acceptance of this PR, will be done at a point in time after 3 weeks later according to our schedule here. Looking cursorily at the change set in #234, your effort obviously evolves SSHKit in a mature direction, generalizing on_std* which I _suppose_ is sufficient to achieve #218. So yes, I'm happy to close #218 given acceptance of this PR, and if anything crops up during the rewrite I can always come back.

Will options[:pty] and on_std* end up being documented?

**Comment by robd** [comment] 2015-04-22 00:43
Hey @vivid-inc 

Yes - I would certainly look to really improve the documentation and add a number of examples, with suitable warnings about the dangers of using pty, to try and help people who want this sort of interactive behaviour.

Just to confirm issue numbers - I think you had a slight typo, but I guess you meant #216 (ie this issue) not #218.

**Comment by vivid-inc** [comment] 2015-04-22 01:09
Great -- And, correct, #216.

**Comment by robd** [comment] 2015-04-27 16:12
Hi @vivid-inc

I have updated #234 with docs and test coverage. I've added some new docs for the proposed new command option here:
https://github.com/robd/sshkit/blob/support-pty-handlers/README.md#interactive-commands

Would welcome any feedback on this over in #234

**Comment by leehambley** [comment] 2015-08-10 09:50
Closed as I think @robd covered most of this in #234 happy to re-open if @vivid-inc comes back!

**Closed by leehambley** 2015-08-10 09:50 UTC

**Comment by jsirex** [comment] 2015-10-22 15:34
Faced same issue with sshkit. I think such solution is more intuitive and native instead of something complex like InteractiveHandler.
Probably, InteractiveHandler is offtopic for such bug.

I think SSH-KIT must be something generic. Providing pipes is really good feature for thinks like
```bash
my cmd | ssh "command"
```

My real use case: add public ssh key to servers. How to do it?
```ruby
..
ssh_key = 'some long ssh key of== user@domain.com:'
# Here is the problem, how to pass to stdin?
@backend.execute(:tee, '-a', '.ssh/authorized_keys')
```

Imagine that program I might want to call doesn't write to stdout/stderr. Interactive handler won't work, will it?

Currently I can do "scp + cat | tee -a"-dance. But, `as` will not work:

```ruby
as :user do
  execute("cat file | tee -a") # not use user
  execute(:cat, "file | tee -a") # will? 
  execute(:cat, "file | sudo #{user} tee -a") # Looks really ugly
end
```

Implementing Additional class only for such simple case is sadly.

**Comment by leehambley** [comment] 2015-10-22 16:04
You would upload the keys to the server with this https://github.com/capistrano/sshkit/blob/master/EXAMPLES.md#upload-a-file-from-a-stream or combine that with this Rake task to compose an `authorized_keys` file from a directory of your developer's keys:

``` ruby
desc "Creates authorized_keys file from keys in authorized_keys/*.pub"
file "authorized_keys" => FileList["authoirzed_keys/*.pub"] do
	sh "cat #{t.prerequisites.join('  ')} > #{t.name}"
end

desc "Uploads the keys, rebuilds the file if it's out of date"
task :upload_keys => 'authorized_keys' do
  on "myserver" do
    as "root" do
      upload! 'authorized_keys', '/the/server/authorized_keys'
    end
  end
end
```

It's simply a matter of looking for the correct solution, sometimes hacking around in shell land playing with streams is the wrong solution.

**Comment by jsirex** [comment] 2015-10-23 10:38
In my case I haven't whole authorized_keys file which I can upload.
I know, that there are many work arounds exist but possibility to control STDIN easily is great.

**Comment by leehambley** [comment] 2015-10-23 11:32
SSHKit is designed to be simple and do the simplest thing most of the time, if you are conditionally remotely building an authorized keys file, and you want to map standard in and out you're outside the realm of what SSHKit was designed for, in that case you can easily access the underlying Net::SSH object and do what you need.

**Comment by jsirex** [comment] 2015-10-23 12:33
@leehambley Looks like I cannot get channel object during `@backend.execute()`.

Appending a string to the file is just one example where stdin can help. I think expose somehow stdin, stdout, stderr to user is more simpler and clear solution instead of creating additional handler class.  Probably, I'm wrong.

**Comment by leehambley** [comment] 2015-10-23 12:50
>  Looks like I cannot get channel object during `@backend.execute()`.

Correct, but you should be able to find it on the `@backend`.

> I think expose somehow stdin, stdout, stderr to user is more simpler and clear solution instead of creating additional handler class. 

It encourages programming without defining the requirement or writing tests, if you have a concrete case of wanting to do something like managing an `authorized_keys` file surely it's worth testing, and probably reusing?

I'm not sure we'll come to agreement, so I'm locking this issue to prevent further discussion, I believe the arguments have been made fairly on both sides, but I'd like to put a stop to a closed discussion on an almost one-year old issue we decided wasn't fixable in a way we could live with.
